-- Add orden column to anestesia_insumos table
ALTER TABLE anestesia_insumos ADD COLUMN IF NOT EXISTS orden INTEGER DEFAULT 0;

-- Add anestesia_principal and anestesia_secundaria to folios table for mixed anesthesia
ALTER TABLE folios ADD COLUMN IF NOT EXISTS anestesia_principal TEXT;
ALTER TABLE folios ADD COLUMN IF NOT EXISTS anestesia_secundaria TEXT;

-- Clear existing data in anestesia_insumos to repopulate with ordered data
TRUNCATE TABLE anestesia_insumos;

-- Now we'll populate anestesia_insumos with data from the Excel files
-- Sedación
INSERT INTO anestesia_insumos (tipo_anestesia, insumo_id, cantidad_default, orden)
SELECT 
  'sedacion' as tipo_anestesia,
  i.id as insumo_id,
  1 as cantidad_default,
  ROW_NUMBER() OVER (ORDER BY i.nombre) as orden
FROM insumos i
WHERE i.nombre IN (
  'CIRCUITO CIRCULAR CERRADO EXPANDIBLE (ADULTO)',
  'ELECTRODOS PARA ELECTROCARDIOGRAMA CON SOPORTE ADHESIVO RECUBIERTOS DE AG E HIDROGEL CONDUCTOR',
  'CATETER PARA VENOCLISIS MEDIDAS: 18G',
  'EQUIPO PARA VENOCLISIS NORMOGOTERO',
  'JERINGA DE PLASTICO CON CAPACIDAD DE 10ML CON AGUJA DE 21G',
  'JERINGA DE PLASTICO CON CAPACIDAD DE 20ML SIN AGUJA',
  'JERINGA DE PLASTICO CON CAPACIDAD DE 5ML CON AGUJA 20G',
  'MASCARILLA FACIAL PARA ADMINISTRACIÓN DE OXÍGENO CON ALMOHADILLA Y VALVULA PARA INFLADO TAMAÑOS 3',
  'PROPOFOL. EMULSIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: PROPOFOL  200 MG. EN EMULSIÓN CON O SIN EDETATO DISÓDICO (DIHIDRATADO). ENVASE CON 5 AMPOLLETAS O FRASCOS ÁMPULA DE 20 ML.',
  'MIDAZOLAM. SOLUCIÓN INYECTABLE CADA AMPOLLETA CONTIENE: CLORHIDRATO DE MIDAZOLAM EQUIVALENTE A 5 MG DE MIDAZOLAM O MIDAZOLAM 5 MG ENVASE CON 5 A',
  'FENTANILO. SOLUCIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: CITRATO DE FENTANILO EQUIVALENTE A 0.5 MG DE FENTANILO. ENVASE CON 6 AMPOLLETAS O FRASCOS ÁMPULA CON 10 ML.',
  'ONDANSETRÓN. SOLUCIÓN INYECTABLE CADA AMPOLLETA O FRASCO AMPULA CONTIENE: CLORHIDRATO DIHIDRATADO DE ONDANSETRÓN EQUIVALENTE A 8 MG DE ONDANSETRÓN ENVASE CON 3 AMPOLLETAS O FRASCOS ÁMPULA CON 4 ML.'
)
LIMIT 50;

-- Loco Regional
INSERT INTO anestesia_insumos (tipo_anestesia, insumo_id, cantidad_default, orden)
SELECT 
  'loco_regional' as tipo_anestesia,
  i.id as insumo_id,
  1 as cantidad_default,
  ROW_NUMBER() OVER (ORDER BY i.nombre) as orden
FROM insumos i
WHERE i.nombre IN (
  'ELECTRODOS PARA ELECTROCARDIOGRAMA CON SOPORTE ADHESIVO RECUBIERTOS DE AG E HIDROGEL CONDUCTOR',
  'CATETER PARA VENOCLISIS MEDIDAS: 18G',
  'EQUIPO PARA VENOCLISIS NORMOGOTERO',
  'JERINGA DE PLASTICO CON CAPACIDAD DE 10ML CON AGUJA DE 21G',
  'AGUJA WHITACRE PARA RAQUIANESTESIA CON PUNTA TIPO LÁPIZ CALIBRES: 25G LONGITUD 8.7 A 9.1CM',
  'MIDAZOLAM. SOLUCIÓN INYECTABLE CADA AMPOLLETA CONTIENE: CLORHIDRATO DE MIDAZOLAM EQUIVALENTE A 5 MG DE MIDAZOLAM O MIDAZOLAM 5 MG ENVASE CON 5 A',
  'FENTANILO. SOLUCIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: CITRATO DE FENTANILO EQUIVALENTE A 0.5 MG DE FENTANILO. ENVASE CON 6 AMPOLLETAS O FRASCOS ÁMPULA CON 10 ML.',
  'LIDOCAÍNA. SOLUCIÓN INYECTABLE AL 2%. CADA FRASCO ÁMPULA CONTIENE: CLORHIDRATO DE LIDOCAÍNA 1 G ENVASE CON 5 FRASCOS ÁMPULA CON 50 ML'
)
LIMIT 50;

-- General Balanceada Adulto
INSERT INTO anestesia_insumos (tipo_anestesia, insumo_id, cantidad_default, orden)
SELECT 
  'general_balanceada_adulto' as tipo_anestesia,
  i.id as insumo_id,
  1 as cantidad_default,
  ROW_NUMBER() OVER (ORDER BY i.nombre) as orden
FROM insumos i
WHERE i.nombre IN (
  'CIRCUITO CIRCULAR CERRADO EXPANDIBLE (ADULTO)',
  'TUBO ENDOTRAQUEAL DE PLASTICO GRADO MEDICO CON GLOBO TAMAÑO: 7.0',
  'TUBO ENDOTRAQUEAL DE PLASTICO GRADO MEDICO CON GLOBO TAMAÑO: 7.5',
  'ELECTRODOS PARA ELECTROCARDIOGRAMA CON SOPORTE ADHESIVO RECUBIERTOS DE AG E HIDROGEL CONDUCTOR',
  'CATETER PARA VENOCLISIS MEDIDAS: 18G',
  'EQUIPO PARA VENOCLISIS NORMOGOTERO',
  'JERINGA DE PLASTICO CON CAPACIDAD DE 10ML CON AGUJA DE 21G',
  'PROPOFOL. EMULSIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: PROPOFOL  200 MG. EN EMULSIÓN CON O SIN EDETATO DISÓDICO (DIHIDRATADO). ENVASE CON 5 AMPOLLETAS O FRASCOS ÁMPULA DE 20 ML.',
  'FENTANILO. SOLUCIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: CITRATO DE FENTANILO EQUIVALENTE A 0.5 MG DE FENTANILO. ENVASE CON 6 AMPOLLETAS O FRASCOS ÁMPULA CON 10 ML.'
)
LIMIT 50;

-- General Balanceada Pediátrica  
INSERT INTO anestesia_insumos (tipo_anestesia, insumo_id, cantidad_default, orden)
SELECT 
  'general_balanceada_pediatrica' as tipo_anestesia,
  i.id as insumo_id,
  1 as cantidad_default,
  ROW_NUMBER() OVER (ORDER BY i.nombre) as orden
FROM insumos i
WHERE i.nombre IN (
  'CIRCUITO CIRCULAR CERRADO EXPANDIBLE CON : (PEDIÁTRICO)',
  'TUBO ENDOTRAQUEAL DE PLASTICO GRADO MEDICO CON GLOBO TAMAÑO: 5.0',
  'TUBO ENDOTRAQUEAL DE PLASTICO GRADO MEDICO SIN GLOBO TAMAÑO: 4.0',
  'ELECTRODOS PARA ELECTROCARDIOGRAMA CON SOPORTE ADHESIVO RECUBIERTOS DE AG E HIDROGEL CONDUCTOR',
  'CATETER PARA VENOCLISIS MEDIDAS: 22G',
  'EQUIPO PARA VENOCLISIS MICROGOTERO',
  'JERINGA DE PLASTICO CON CAPACIDAD DE 5ML CON AGUJA 20G',
  'PROPOFOL. EMULSIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: PROPOFOL  200 MG. EN EMULSIÓN CON O SIN EDETATO DISÓDICO (DIHIDRATADO). ENVASE CON 5 AMPOLLETAS O FRASCOS ÁMPULA DE 20 ML.',
  'FENTANILO. SOLUCIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: CITRATO DE FENTANILO EQUIVALENTE A 0.5 MG DE FENTANILO. ENVASE CON 6 AMPOLLETAS O FRASCOS ÁMPULA CON 10 ML.'
)
LIMIT 50;

-- General Endovenosa
INSERT INTO anestesia_insumos (tipo_anestesia, insumo_id, cantidad_default, orden)
SELECT 
  'general_endovenosa' as tipo_anestesia,
  i.id as insumo_id,
  1 as cantidad_default,
  ROW_NUMBER() OVER (ORDER BY i.nombre) as orden
FROM insumos i
WHERE i.nombre IN (
  'CIRCUITO CIRCULAR CERRADO EXPANDIBLE (ADULTO)',
  'TUBO ENDOTRAQUEAL DE PLASTICO GRADO MEDICO CON GLOBO TAMAÑO: 7.0',
  'ELECTRODOS PARA ELECTROCARDIOGRAMA CON SOPORTE ADHESIVO RECUBIERTOS DE AG E HIDROGEL CONDUCTOR',
  'CATETER PARA VENOCLISIS MEDIDAS: 18G',
  'EQUIPO PARA VENOCLISIS NORMOGOTERO',
  'JERINGA DE PLASTICO CON CAPACIDAD DE 10ML CON AGUJA DE 21G',
  'PROPOFOL. EMULSIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: PROPOFOL  200 MG. EN EMULSIÓN CON O SIN EDETATO DISÓDICO (DIHIDRATADO). ENVASE CON 5 AMPOLLETAS O FRASCOS ÁMPULA DE 20 ML.',
  'FENTANILO. SOLUCIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: CITRATO DE FENTANILO EQUIVALENTE A 0.5 MG DE FENTANILO. ENVASE CON 6 AMPOLLETAS O FRASCOS ÁMPULA CON 10 ML.'
)
LIMIT 50;

-- Alta Especialidad
INSERT INTO anestesia_insumos (tipo_anestesia, insumo_id, cantidad_default, orden)
SELECT 
  'alta_especialidad' as tipo_anestesia,
  i.id as insumo_id,
  1 as cantidad_default,
  ROW_NUMBER() OVER (ORDER BY i.nombre) as orden
FROM insumos i
WHERE i.nombre IN (
  'CIRCUITO CIRCULAR CERRADO EXPANDIBLE (ADULTO)',
  'TUBO ENDOTRAQUEAL DE PLASTICO GRADO MEDICO CON GLOBO TAMAÑO: 7.5',
  'ELECTRODOS PARA ELECTROCARDIOGRAMA CON SOPORTE ADHESIVO RECUBIERTOS DE AG E HIDROGEL CONDUCTOR',
  'CATETER PARA VENOCLISIS MEDIDAS: 16G',
  'EQUIPO PARA VENOCLISIS NORMOGOTERO',
  'JERINGA DE PLASTICO CON CAPACIDAD DE 20ML SIN AGUJA',
  'PROPOFOL. EMULSIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: PROPOFOL  200 MG. EN EMULSIÓN CON O SIN EDETATO DISÓDICO (DIHIDRATADO). ENVASE CON 5 AMPOLLETAS O FRASCOS ÁMPULA DE 20 ML.',
  'FENTANILO. SOLUCIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: CITRATO DE FENTANILO EQUIVALENTE A 0.5 MG DE FENTANILO. ENVASE CON 6 AMPOLLETAS O FRASCOS ÁMPULA CON 10 ML.'
)
LIMIT 50;

-- Alta Especialidad Trasplante Renal
INSERT INTO anestesia_insumos (tipo_anestesia, insumo_id, cantidad_default, orden)
SELECT 
  'alta_especialidad_trasplante' as tipo_anestesia,
  i.id as insumo_id,
  1 as cantidad_default,
  ROW_NUMBER() OVER (ORDER BY i.nombre) as orden
FROM insumos i
WHERE i.nombre IN (
  'CIRCUITO CIRCULAR CERRADO EXPANDIBLE (ADULTO)',
  'TUBO ENDOTRAQUEAL DE PLASTICO GRADO MEDICO CON GLOBO TAMAÑO: 7.5',
  'ELECTRODOS PARA ELECTROCARDIOGRAMA CON SOPORTE ADHESIVO RECUBIERTOS DE AG E HIDROGEL CONDUCTOR',
  'CATETER PARA VENOCLISIS MEDIDAS: 16G',
  'EQUIPO PARA VENOCLISIS NORMOGOTERO',
  'JERINGA DE PLASTICO CON CAPACIDAD DE 20ML SIN AGUJA',
  'PROPOFOL. EMULSIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: PROPOFOL  200 MG. EN EMULSIÓN CON O SIN EDETATO DISÓDICO (DIHIDRATADO). ENVASE CON 5 AMPOLLETAS O FRASCOS ÁMPULA DE 20 ML.',
  'FENTANILO. SOLUCIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: CITRATO DE FENTANILO EQUIVALENTE A 0.5 MG DE FENTANILO. ENVASE CON 6 AMPOLLETAS O FRASCOS ÁMPULA CON 10 ML.'
)
LIMIT 50;

-- Cuidados Anestésicos Monitoreados
INSERT INTO anestesia_insumos (tipo_anestesia, insumo_id, cantidad_default, orden)
SELECT 
  'cuidados_anestesicos' as tipo_anestesia,
  i.id as insumo_id,
  1 as cantidad_default,
  ROW_NUMBER() OVER (ORDER BY i.nombre) as orden
FROM insumos i
WHERE i.nombre IN (
  'CIRCUITO CIRCULAR CERRADO EXPANDIBLE (ADULTO)',
  'ELECTRODOS PARA ELECTROCARDIOGRAMA CON SOPORTE ADHESIVO RECUBIERTOS DE AG E HIDROGEL CONDUCTOR',
  'CATETER PARA VENOCLISIS MEDIDAS: 18G',
  'EQUIPO PARA VENOCLISIS NORMOGOTERO',
  'JERINGA DE PLASTICO CON CAPACIDAD DE 10ML CON AGUJA DE 21G',
  'PROPOFOL. EMULSIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: PROPOFOL  200 MG. EN EMULSIÓN CON O SIN EDETATO DISÓDICO (DIHIDRATADO). ENVASE CON 5 AMPOLLETAS O FRASCOS ÁMPULA DE 20 ML.',
  'MIDAZOLAM. SOLUCIÓN INYECTABLE CADA AMPOLLETA CONTIENE: CLORHIDRATO DE MIDAZOLAM EQUIVALENTE A 5 MG DE MIDAZOLAM O MIDAZOLAM 5 MG ENVASE CON 5 A',
  'FENTANILO. SOLUCIÓN INYECTABLE CADA AMPOLLETA O FRASCO ÁMPULA CONTIENE: CITRATO DE FENTANILO EQUIVALENTE A 0.5 MG DE FENTANILO. ENVASE CON 6 AMPOLLETAS O FRASCOS ÁMPULA CON 10 ML.'
)
LIMIT 50;